//! Build script: embed mordant's wheel theme files as
//! `BUNDLED_THEMES: &[(&str, &str)]` — no new deps, std + shell tools only.
//!
//! The theme files live upstream, not in this repo:
//! `mordant-py/mordant/themes/` at the pinned tag of
//! https://github.com/opticsWolf/mordant (see assets/ATTRIBUTION.md).
//!
//! Sources, in order:
//! 1. `MORDANT_THEMES_DIR` — local directory override (offline dev,
//!    e.g. a sibling mordant checkout's `mordant-py/mordant/themes/`).
//! 2. A previous build's download already in `OUT_DIR/themes`
//!    (offline rebuilds keep working).
//! 3. Fresh tarball download from GitHub (`curl`, else PowerShell
//!    `Invoke-WebRequest`; extraction via `tar`, both inbox on Windows).
//!
//! Total failure degrades loudly but non-fatally: the build succeeds with
//! an empty bundled set (a warning is printed; tests assert non-empty, so
//! CI catches it). `MORDANT_THEMES_REV` overrides the pinned tag.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const REPO: &str = "opticsWolf/mordant";
const THEMES_PATH: &str = "mordant-py/mordant/themes";
const DEFAULT_REV: &str = "v0.10.0";

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=bundled_themes.txt");
    println!("cargo::rerun-if-env-changed=MORDANT_THEMES_DIR");
    println!("cargo::rerun-if-env-changed=MORDANT_THEMES_REV");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("themes");

    let have = populate(&dest);
    if !have {
        println!(
            "cargo::warning=kilim: theme download failed and no cache present; \
             building WITHOUT bundled wheel themes (set MORDANT_THEMES_DIR to fix offline)"
        );
    }

    // Generate the include table: ONLY the allowlisted stems
    // (bundled_themes.txt) — the registry ships exactly the Kilim ten.
    let allow: std::collections::HashSet<String> = std::fs::read_to_string(
        Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("bundled_themes.txt"),
    )
    .unwrap_or_default()
    .lines()
    .map(str::trim)
    .filter(|l| !l.is_empty() && !l.starts_with('#'))
    // Entries are filenames; match against file stems.
    .map(|l| l.rfind('.').map(|i| &l[..i]).unwrap_or(l).to_string())
    .collect();
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dest)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| {
                    let stem_ok = p
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .is_some_and(|s| allow.contains(s));
                    stem_ok
                        && p.extension().and_then(|e| e.to_str()).is_some_and(|e| {
                            e.eq_ignore_ascii_case("tmtheme") || e.eq_ignore_ascii_case("json")
                        })
                })
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    let mut entries = String::new();
    for path in &files {
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("?");
        let file = path.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let _ = writeln!(
            entries,
            "    (\"{name}\", include_str!(concat!(env!(\"OUT_DIR\"), \"/themes/{file}\"))),",
            name = rs_escape(stem),
            file = rs_escape(file),
        );
    }
    let code = format!(
        "// Generated by build.rs — mordant wheel themes fetched from GitHub\n\
         // (see crates/kilim-core/assets/ATTRIBUTION.md). {n} files.\n\
         pub const BUNDLED_THEMES: &[(&str, &str)] = &[\n{entries}];\n",
        n = files.len(),
    );
    std::fs::write(out_dir.join("bundled_themes.rs"), code).unwrap();
}

/// Fill `dest` with theme files. Returns true if any are present afterwards.
fn populate(dest: &Path) -> bool {
    // 1. Explicit local override.
    if let Ok(dir) = std::env::var("MORDANT_THEMES_DIR") {
        if copy_themes(Path::new(&dir), dest) {
            return true;
        }
        println!("cargo::warning=kilim: MORDANT_THEMES_DIR={dir} has no theme files");
    }
    // 2. Reuse a previous download (offline-friendly).
    if dir_has_themes(dest) {
        return true;
    }
    // 3. Fresh download.
    let rev = std::env::var("MORDANT_THEMES_REV").unwrap_or_else(|_| DEFAULT_REV.to_string());
    if download_themes(&rev, dest) {
        return true;
    }
    dir_has_themes(dest)
}

fn dir_has_themes(dir: &Path) -> bool {
    std::fs::read_dir(dir).map(|rd| {
        rd.flatten().any(|e| {
            e.path()
                .extension()
                .and_then(|x| x.to_str())
                .is_some_and(|x| x.eq_ignore_ascii_case("tmtheme") || x.eq_ignore_ascii_case("json"))
        })
    }).unwrap_or(false)
}

fn copy_themes(src: &Path, dest: &Path) -> bool {
    let mut n = 0;
    if let Ok(rd) = std::fs::read_dir(src) {
        std::fs::create_dir_all(dest).ok();
        for entry in rd.flatten() {
            let p = entry.path();
            let is_theme = p
                .extension()
                .and_then(|x| x.to_str())
                .is_some_and(|x| x.eq_ignore_ascii_case("tmtheme") || x.eq_ignore_ascii_case("json"));
            if is_theme && p.is_file() {
                if std::fs::copy(&p, dest.join(p.file_name().unwrap())).is_ok() {
                    n += 1;
                }
            }
        }
    }
    n > 0
}

/// Download the repo tarball for `rev`, extract just the themes dir.
fn download_themes(rev: &str, dest: &Path) -> bool {
    // codeload redirects to a CDN; curl follows with -L.
    let url = format!("https://codeload.github.com/{REPO}/tar.gz/refs/tags/{rev}");
    let tmp = std::env::temp_dir().join(format!("kilim-mordant-themes-{rev}.tar.gz"));
    let tmp_str = tmp.to_string_lossy().into_owned();

    let fetched = run("curl", &["-sSL", "--fail", "-o", &tmp_str, &url])
        || run(
            "powershell",
            &[
                "-NoProfile",
                "-Command",
                &format!("Invoke-WebRequest -Uri '{url}' -OutFile '{tmp_str}'"),
            ],
        );
    if !fetched {
        println!("cargo::warning=kilim: could not download {url}");
        return false;
    }
    std::fs::create_dir_all(dest).ok();
    // Extract the whole tarball (<1MB) and pick the themes dir in Rust:
    // avoids pattern-flag dialects entirely (bsdtar wants --wildcards,
    // old GNU tars reject it).
    let exdir = std::env::temp_dir().join(format!("kilim-mordant-src-{rev}"));
    let _ = std::fs::remove_dir_all(&exdir);
    std::fs::create_dir_all(&exdir).ok();
    let out = std::process::Command::new("tar")
        .args(["-xzf", &tmp_str, "-C", &exdir.to_string_lossy()])
        .output();
    let _ = std::fs::remove_file(&tmp);
    match out {
        Ok(o) if o.status.success() => {}
        Ok(o) => {
            let err = String::from_utf8_lossy(&o.stderr);
            println!(
                "cargo::warning=kilim: could not extract themes tarball: {}",
                err.lines().next().unwrap_or("(no stderr)").chars().take(300).collect::<String>()
            );
            return false;
        }
        Err(e) => {
            println!("cargo::warning=kilim: could not run tar: {e}");
            return false;
        }
    }
    // <exdir>/mordant-<rev>/mordant-py/mordant/themes
    let mut found = false;
    if let Ok(rd) = std::fs::read_dir(&exdir) {
        for root in rd.flatten() {
            let themes = root.path().join(THEMES_PATH);
            if themes.is_dir() && copy_themes(&themes, dest) {
                found = true;
            }
        }
    }
    let _ = std::fs::remove_dir_all(&exdir);
    if !found {
        println!("cargo::warning=kilim: themes dir missing in tarball");
    }
    found
}

fn run(cmd: &str, args: &[&str]) -> bool {
    std::process::Command::new(cmd)
        .args(args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn rs_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c => out.push(c),
        }
    }
    out
}
