//! Syntax highlighting — syntect directly (not syntect-py, not mordant-by-default).
//!
//! - Code/file panes: syntect + default syntaxes/themes (fancy-regex, no native onig).
//! - Markdown panes (optional `markdown` feature): delegate to mordant's
//!   `highlighter` engine, which is itself syntect + VSCode-theme conversion.
//! - Theme names are shared so `set_theme("Dracula")` means the same in
//!   ratatui and Lace.

use std::sync::{OnceLock, RwLock};
use syntect::highlighting::ThemeSet;
use syntect::parsing::SyntaxSet;

// Vendored wheel themes (generated by build.rs from assets/themes/).
#[cfg(feature = "markdown")]
include!(concat!(env!("OUT_DIR"), "/bundled_themes.rs"));

static SYNTAXES: OnceLock<SyntaxSet> = OnceLock::new();
static THEMES: OnceLock<RwLock<ThemeSet>> = OnceLock::new();

fn syntaxes() -> &'static SyntaxSet {
    SYNTAXES.get_or_init(SyntaxSet::load_defaults_newlines)
}

fn themes() -> &'static RwLock<ThemeSet> {
    // Starts EMPTY: the registry ships exactly the Kilim ten plus
    // explicit customs (register_custom_theme / ~/.mordant). syntect's
    // load_defaults (Solarized, InspiredGitHub, base16s) is deliberately
    // NOT the base — those names must stay unresolvable.
    THEMES.get_or_init(|| RwLock::new(ThemeSet { themes: std::collections::BTreeMap::new() }))
}

/// One styled text run. Both frontends map this to native spans:
/// ratatui `Span::styled` / Qt `QTextCharFormat`.
#[derive(Debug, Clone)]
pub struct StyledSpan {
    pub text: String,
    pub fg: String,
    pub bg: String,
    pub bold: bool,
    pub italic: bool,
    pub underline: bool,
}

pub struct ThemeRegistry;

impl ThemeRegistry {
    pub fn list_themes() -> Vec<String> {
        let ts = themes().read().unwrap();
        let mut names: Vec<String> = ts.themes.keys().cloned().collect();
        names.sort();
        names
    }

    /// Clone a theme from our registry (bat assets + customs included).
    pub fn resolve(name: &str) -> Option<syntect::highlighting::Theme> {
        themes().read().unwrap().themes.get(name).cloned()
    }

    /// Theme foreground as `#rrggbb` (for terminal default cells). Same
    /// fallback as `background`.
    pub fn foreground(theme_name: &str) -> Option<String> {
        let ts = themes().read().unwrap();
        #[cfg(feature = "markdown")]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.get("Kilim Midnight"));
        #[cfg(not(feature = "markdown"))]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.values().next());
        let fg = theme?.settings.foreground?;
        Some(format!("#{:02x}{:02x}{:02x}", fg.r, fg.g, fg.b))
    }

    /// Theme background as `#rrggbb` (for full-bleed Qt panes).
    pub fn background(theme_name: &str) -> Option<String> {
        let ts = themes().read().unwrap();
        // Same fallback as highlight(): unknown names resolve to the
        // default, so callers (TUI fill, Qt panes, page chrome) agree.
        #[cfg(feature = "markdown")]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.get("Kilim Midnight"));
        #[cfg(not(feature = "markdown"))]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.values().next());
        let bg = theme?.settings.background?;
        Some(format!("#{:02x}{:02x}{:02x}", bg.r, bg.g, bg.b))
    }

    /// Highlight `code` in `lang` (token or extension, e.g. "python"/"py").
    /// Falls back to plain text — never errors.
    pub fn highlight(lang: &str, code: &str, theme_name: &str) -> Vec<Vec<StyledSpan>> {
        use syntect::easy::HighlightLines;
        use syntect::util::LinesWithEndings;

        let ps = syntaxes();
        let syntax = ps
            .find_syntax_by_token(lang)
            .or_else(|| ps.find_syntax_by_extension(lang))
            .unwrap_or_else(|| ps.find_syntax_plain_text());

        let ts = themes().read().unwrap();
        // Unknown names fall back to Kilim Midnight (always in-registry when
        // the markdown feature is on) — never to a name outside the
        // shipped set. A bare registry (no markdown, no customs) yields
        // unstyled lines instead of panicking.
        #[cfg(feature = "markdown")]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.get("Kilim Midnight"));
        #[cfg(not(feature = "markdown"))]
        let theme = ts.themes.get(theme_name).or_else(|| ts.themes.values().next());
        let Some(theme) = theme else {
            return code
                .lines()
                .map(|l| {
                    vec![StyledSpan {
                        text: l.to_string(),
                        fg: String::new(),
                        bg: String::new(),
                        bold: false,
                        italic: false,
                        underline: false,
                    }]
                })
                .collect();
        };

        let mut out: Vec<Vec<StyledSpan>> = Vec::new();
        let mut h = HighlightLines::new(syntax, theme);
        for line in LinesWithEndings::from(code) {
            let mut row = Vec::new();
            match h.highlight_line(line, ps) {
                Ok(ranges) => {
                    for (style, text) in ranges {
                        row.push(StyledSpan {
                            text: text.to_string(),
                            fg: format!(
                                "#{:02x}{:02x}{:02x}",
                                style.foreground.r, style.foreground.g, style.foreground.b
                            ),
                            bg: format!(
                                "#{:02x}{:02x}{:02x}",
                                style.background.r, style.background.g, style.background.b
                            ),
                            bold: style
                                .font_style
                                .contains(syntect::highlighting::FontStyle::BOLD),
                            italic: style
                                .font_style
                                .contains(syntect::highlighting::FontStyle::ITALIC),
                            underline: style
                                .font_style
                                .contains(syntect::highlighting::FontStyle::UNDERLINE),
                        });
                    }
                }
                Err(_) => row.push(StyledSpan {
                    text: line.to_string(),
                    fg: "#000000".into(),
                    bg: "#ffffff".into(),
                    bold: false,
                    italic: false,
                    underline: false,
                }),
            }
            out.push(row);
        }
        out
    }

    /// Register a custom theme under `name` so both frontends see it.
    /// Accepts `.tmTheme` plist everywhere; VSCode JSON additionally works
    /// with the `markdown` feature (mordant's converter), in which case the
    /// converted theme is mirrored into both registries via `resolve_theme`.
    pub fn register_custom_theme(name: &str, content: &str) -> Result<(), String> {
        let t = Self::parse_theme_content(content)?;
        themes().write().unwrap().themes.insert(name.to_string(), t);
        #[cfg(feature = "markdown")]
        let _ = mordant::highlighter::register_custom_theme(name, content);
        Ok(())
    }

    /// Parse plist or VSCode JSON into a Theme WITHOUT registering it.
    /// Bases for the Kilim set use this (they never enter the registry).
    /// Requires the `markdown` feature for the JSON path.
    #[cfg(feature = "markdown")]
    fn parse_theme_content(content: &str) -> Result<syntect::highlighting::Theme, String> {
        // Fast path: plist parses natively with syntect alone.
        let mut reader = std::io::Cursor::new(content.as_bytes());
        if let Ok(t) = ThemeSet::load_from_reader(&mut reader) {
            return Ok(t);
        }
        // VSCode JSON path — needs mordant's converter (scratch name,
        // resolved then forgotten; see PARSE_PROBE).
        {
            mordant::highlighter::register_custom_theme(PARSE_PROBE, content)?;
            mordant::highlighter::resolve_theme(PARSE_PROBE)
                .ok_or_else(|| "registered probe but could not resolve it".to_string())
        }
    }

    /// Parse without the markdown feature: plist only.
    #[cfg(not(feature = "markdown"))]
    fn parse_theme_content(content: &str) -> Result<syntect::highlighting::Theme, String> {
        let mut reader = std::io::Cursor::new(content.as_bytes());
        ThemeSet::load_from_reader(&mut reader)
            .map_err(|_| "not a .tmTheme plist; VSCode JSON themes need the `markdown` feature".to_string())
    }

    pub fn list_syntaxes() -> Vec<String> {
        syntaxes().syntaxes().iter().map(|s| s.name.clone()).collect()
    }

    /// Import the shipped theme set: exactly the ten Kilim themes
    /// (five palettes x standard/neo) built from bat + wheel bases.
    /// Bases are NEVER registered and user customs (~/.mordant/themes)
    /// are NEVER auto-imported — the app exposes only Kilim themes
    /// (`register_custom_theme` stays as the explicit opt-in). Also
    /// registers our registry as mordant's mermaid theme resolver
    /// (md_viewer's "sync"). Requires the `markdown` feature.
    /// Names present win.
    #[cfg(feature = "markdown")]
    pub fn import_mordant_themes() {
        mordant::mermaid_theme::register_syntax_theme_lookup(lookup_syntax_theme);
        // Bases into a LOCAL map (membership-checked: assets.get_theme
        // falls back silently, which would poison names). Never inserted.
        let mut extra = std::collections::HashMap::new();
        let assets = syntect_assets::assets::HighlightingAssets::from_binary();
        let have: std::collections::HashSet<&str> = assets.themes().collect();
        for name in crate::kilim_themes::BAT_BASES {
            if have.contains(name) {
                extra.insert(name.to_string(), assets.get_theme(name).clone());
            }
        }
        for (name, theme) in bundled_themes() {
            extra.entry(name).or_insert(theme);
        }
        // Kilim ten last: mirror closure only touches mordant's lock;
        // ours is held — the same ours->mordant order
        // register_custom_theme uses, so no cycle.
        crate::kilim_themes::ensure_kilim_themes(
            &extra,
            &mut themes().write().unwrap(),
            |n, x| mordant::highlighter::register_custom_theme(n, x),
        );
    }
}

/// Parse the allowlisted wheel files WITHOUT registering them: bases
/// for the Kilim set only. Failures warn and skip (offline-degraded).
/// Requires the `markdown` feature.
#[cfg(feature = "markdown")]
fn bundled_themes() -> Vec<(String, syntect::highlighting::Theme)> {
    let mut out = Vec::new();
    for (name, content) in BUNDLED_THEMES {
        match ThemeRegistry::parse_theme_content(content) {
            Ok(t) => out.push((name.to_string(), t)),
            Err(e) => eprintln!("kilim: could not load bundled theme {name}: {e}"),
        }
    }
    out
}

/// Scratch name used to parse VSCode JSON through mordant's converter
/// (its only ingestion API). Never a real theme: the customs importer
/// skips it, so a parallel import racing the parse can't adopt it.
#[cfg(feature = "markdown")]
const PARSE_PROBE: &str = "kilim-parse-probe";

/// Non-capturing resolver hook for mordant's mermaid derivation:
/// `register_syntax_theme_lookup` takes a bare fn pointer, so this reads
/// the process-global registry instead of closing over anything.
#[cfg(feature = "markdown")]
fn lookup_syntax_theme(name: &str) -> Option<syntect::highlighting::Theme> {
    themes().read().ok()?.themes.get(name).cloned()
}

/// Serialize a syntect `Theme` to `.tmTheme` plist XML.
///
/// Bridges registries that only ingest file content (mordant's
/// `register_custom_theme`) with themes we hold as structs (bat assets).
/// Covers global colors + per-scope fg/bg/fontStyle; exotic UI keys
/// (bracket/tag options, guides) and alpha channels are dropped — code
/// colors round-trip exactly.
#[cfg(feature = "markdown")]
pub(crate) fn theme_to_tmtheme(name: &str, theme: &syntect::highlighting::Theme) -> String {
    use syntect::highlighting::FontStyle;
    use std::fmt::Write as _;

    fn css(c: syntect::highlighting::Color) -> String {
        format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
    }
    fn esc(s: &str) -> String {
        s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
    }
    fn font_style(fs: FontStyle) -> String {
        let mut parts = Vec::new();
        if fs.contains(FontStyle::BOLD) {
            parts.push("bold");
        }
        if fs.contains(FontStyle::ITALIC) {
            parts.push("italic");
        }
        if fs.contains(FontStyle::UNDERLINE) {
            parts.push("underline");
        }
        parts.join(" ")
    }
    // ScopeStack Display joins with spaces (= tmTheme stack syntax);
    // excludes serialize as `path -excluded`.
    fn selector(sels: &syntect::highlighting::ScopeSelectors) -> String {
        sels.selectors
            .iter()
            .map(|s| {
                let mut out = s.path.to_string();
                for ex in &s.excludes {
                    out.push_str(" -");
                    out.push_str(&ex.to_string());
                }
                out.trim_end().to_string()
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    let st = &theme.settings;
    let mut globals = String::new();
    let mut kv = |key: &str, c: Option<syntect::highlighting::Color>| {
        if let Some(c) = c {
            let _ = writeln!(globals, "                    <key>{key}</key><string>{}</string>", css(c));
        }
    };
    kv("foreground", st.foreground);
    kv("background", st.background);
    kv("caret", st.caret);
    kv("lineHighlight", st.line_highlight);
    kv("selection", st.selection);
    kv("selectionForeground", st.selection_foreground);
    kv("gutter", st.gutter);
    kv("gutterForeground", st.gutter_foreground);
    kv("findHighlight", st.find_highlight);

    let mut rules = String::new();
    for item in &theme.scopes {
        let style = &item.style;
        let mut inner = String::new();
        if let Some(c) = style.foreground {
            let _ = writeln!(inner, "                        <key>foreground</key><string>{}</string>", css(c));
        }
        if let Some(c) = style.background {
            let _ = writeln!(inner, "                        <key>background</key><string>{}</string>", css(c));
        }
        if let Some(fs) = style.font_style {
            if !fs.is_empty() {
                let _ = writeln!(inner, "                        <key>fontStyle</key><string>{}</string>", font_style(fs));
            }
        }
        let _ = writeln!(
            rules,
            "                <dict><key>scope</key><string>{}</string>\
                 <key>settings</key><dict>{}</dict></dict>",
            esc(&selector(&item.scope)),
            inner.trim_end()
        );
    }

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\
         <plist version=\"1.0\"><dict>\
         <key>name</key><string>{}</string>\
         <key>settings</key><array>\
         <dict><key>settings</key><dict>{}</dict></dict>\
         {}</array></dict></plist>",
        esc(name),
        globals.trim_end(),
        rules.trim_end()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn highlights_python_without_panic() {
        let rows = ThemeRegistry::highlight("python", "x = 1\n", "Kilim Midnight");
        assert_eq!(rows.len(), 1);
        assert!(rows[0].iter().any(|s| s.text.contains('x')));
    }

    #[test]
    fn unknown_lang_falls_back() {
        let rows = ThemeRegistry::highlight("nope-lang", "hi\n", "Kilim Midnight");
        assert_eq!(rows.len(), 1);
    }

    #[test]
    fn garbage_theme_registration_fails() {
        assert!(ThemeRegistry::register_custom_theme("junk", "this is not a theme").is_err());
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn bundled_wheel_themes_match_allowlist() {
        use crate::kilim_themes::KILIM_THEMES;
        ThemeRegistry::import_mordant_themes();
        assert_eq!(
            BUNDLED_THEMES.len(),
            6,
            "bundled_themes.txt controls the table: Night Owl + 5 neo JSONs"
        );
        // Bases are build-only (never registered); the ten built on them are.
        let names = ThemeRegistry::list_themes();
        let mut built = Vec::new();
        for def in KILIM_THEMES {
            built.push(def.syntect_name);
            built.push(def.neo_name);
        }
        for name in built {
            assert!(names.contains(&name.to_string()), "missing built theme {name}");
        }
        // Non-allowlisted wheel files stay out.
        assert!(!names.contains(&"aura-theme".to_string()));
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn kilim_themes_register_both_sides() {
        use crate::kilim_themes::{kilim_theme, KILIM_THEMES};
        ThemeRegistry::import_mordant_themes();
        assert_eq!(KILIM_THEMES.len(), 5);
        for def in KILIM_THEMES {
            // Our registry renders TUI + Qt code panes, standard + neo...
            for name in [def.syntect_name, def.neo_name] {
                let rows = ThemeRegistry::highlight("python", "x = 1\n", name);
                assert_eq!(rows.len(), 1, "{name} highlights");
                // ...and mordant's resolves it for fences (no silent fallback).
                let t = mordant::highlighter::resolve_theme(name)
                    .unwrap_or_else(|| panic!("{name} missing mordant-side"));
                let bg = t.settings.background.expect("kilim themes carry bg");
                assert!(bg.r < 200 || def.is_light, "{name} bg matches polarity");
            }
        }
        assert!(kilim_theme("kilim_midnight").is_some());
        assert!(kilim_theme("kilim_midnight_neo").is_some());
        assert_eq!(kilim_theme("Kilim Warm").unwrap().base_syntect, "gruvbox-dark");
        assert!(kilim_theme("nope").is_none());
        // Neon keys are distinct per palette, syntect names shared.
        let mut neon: Vec<_> = KILIM_THEMES.iter().map(|d| d.neo_key).collect();
        neon.sort();
        neon.dedup();
        assert_eq!(neon.len(), 5);
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn bat_bases_stay_pinned() {
        use crate::kilim_themes::{BAT_BASES, KILIM_THEMES};
        // BUNDLED_THEMES is (stem, content): stems carry no extension.
        let bundled: std::collections::HashSet<&str> =
            BUNDLED_THEMES.iter().map(|(n, _)| *n).collect();
        for def in KILIM_THEMES {
            for base in [def.base_syntect, def.neo_base] {
                let in_bat = BAT_BASES.contains(&base);
                let in_bundled = bundled.contains(base);
                assert!(in_bat != in_bundled, "{base} must come from exactly one source");
            }
        }
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn editor_backgrounds_follow_the_paper_color() {
        use crate::kilim_themes::KILIM_THEMES;
        ThemeRegistry::import_mordant_themes();
        let ts = themes().read().unwrap();
        for def in KILIM_THEMES {
            // One paper color per palette, shared by standard + neo:
            // near-white for lights, deep identity for darks.
            for name in [def.syntect_name, def.neo_name] {
                let bg = ts.themes[name].settings.background.expect("kilim themes carry bg");
                let got = format!("#{:02x}{:02x}{:02x}", bg.r, bg.g, bg.b);
                assert_eq!(got, def.editor_bg, "{name} editor background");
            }
        }
        assert_eq!(ts.themes["Kilim Light"].settings.background, ts.themes["Kilim Light Neo"].settings.background);
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn neo_display_settings_mirror_standard() {
        use crate::kilim_themes::KILIM_THEMES;
        ThemeRegistry::import_mordant_themes();
        let ts = themes().read().unwrap();
        // Neo differs ONLY in token colors: every display setting
        // (line highlight, caret, brackets, …) matches the standard
        // sibling, so background behavior is identical.
        for def in KILIM_THEMES {
            let std = format!("{:?}", ts.themes[def.syntect_name].settings);
            let neo = format!("{:?}", ts.themes[def.neo_name].settings);
            assert_eq!(std, neo, "{} display settings", def.neo_name);
        }
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn background_falls_back_like_highlight() {
        ThemeRegistry::import_mordant_themes();
        let known = ThemeRegistry::background("Kilim Midnight");
        assert!(known.is_some());
        // Unknown names resolve to the default — Qt panes, TUI fill and
        // page chrome can never disagree about the paper color.
        assert_eq!(ThemeRegistry::background("nope"), known);
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn tmtheme_writer_roundtrips_kilim_midnight() {
        use syntect::highlighting::ThemeSet;
        ThemeRegistry::import_mordant_themes();
        // Mordant resolves the shipped name instead of falling back.
        let t = mordant::highlighter::resolve_theme("Kilim Midnight")
            .expect("Kilim Midnight should be mirrored into mordant's set");
        let bg = t.settings.background.expect("Kilim Midnight has a background");
        assert_eq!((bg.r, bg.g, bg.b), (0x10, 0x13, 0x19));
        // Writer output re-parses and preserves scope count.
        let xml = super::theme_to_tmtheme("Kilim Midnight", &t);
        let back = ThemeSet::load_from_reader(&mut std::io::Cursor::new(xml.as_bytes()))
            .expect("generated plist must parse");
        let bg2 = back.settings.background.expect("round-tripped background");
        assert_eq!((bg2.r, bg2.g, bg2.b), (0x10, 0x13, 0x19));
        assert_eq!(back.scopes.len(), t.scopes.len());
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn shipped_set_is_exactly_the_kilim_ten() {
        use crate::kilim_themes::KILIM_THEMES;
        ThemeRegistry::import_mordant_themes();
        let names = ThemeRegistry::list_themes();
        let mut expected = Vec::new();
        for def in KILIM_THEMES {
            expected.push(def.syntect_name.to_string());
            expected.push(def.neo_name.to_string());
        }
        for name in &expected {
            assert!(names.contains(name), "shipped theme missing: {name}");
        }
        // Reduction proof: bases and former members are gone — the ten
        // are BUILT, never registered. Set-difference (not exact length):
        // parallel tests may register customs ("Tiny").
        for gone in ["Dracula", "GitHub", "OneHalfLight", "gruvbox-dark",
                      "Night Owl-color-theme", "tokyo-night-light-color-theme",
                      "ayu-light", "LaserWave-color-theme", "Solarized (dark)",
                      "InspiredGitHub", "aura-theme", "tokyo-night-color-theme",
                      "Visual Studio Dark+", "OneDark-Pro", "Monokai Extended"] {
            assert!(!names.contains(&gone.to_string()), "unshipped theme leaked: {gone}");
        }
        let extra: Vec<_> = names.iter().filter(|n| !expected.contains(n) && n.as_str() != "Tiny").collect();
        assert!(extra.is_empty(), "unexpected extras: {extra:?}");
        // And every shipped name highlights + resolves mordant-side.
        for name in &expected {
            let rows = ThemeRegistry::highlight("python", "x = 1\n", name);
            assert_eq!(rows.len(), 1, "{name} highlights");
            assert!(
                mordant::highlighter::resolve_theme(name).is_some(),
                "{name} missing mordant-side"
            );
        }
    }

    #[test]
    #[cfg(feature = "markdown")]
    fn vscode_json_theme_registers_and_highlights() {
        let vscode = r##"{
            "name": "Tiny",
            "type": "dark",
            "colors": { "editor.background": "#1e1e1e", "editor.foreground": "#d4d4d4" },
            "tokenColors": [
                { "scope": "comment", "settings": { "foreground": "#6a9955" } },
                { "settings": { "foreground": "#d4d4d4", "background": "#1e1e1e" } }
            ]
        }"##;
        ThemeRegistry::register_custom_theme("Tiny", vscode).unwrap();
        assert!(ThemeRegistry::list_themes().contains(&"Tiny".to_string()));
        let rows = ThemeRegistry::highlight("python", "# c\nx = 1\n", "Tiny");
        assert_eq!(rows.len(), 2);
    }


    #[test]
    #[cfg(feature = "markdown")]
    fn functional_elements_have_distinct_colors() {
        use crate::kilim_themes::KILIM_THEMES;
        ThemeRegistry::import_mordant_themes();
        let rust = r#"// c
pub fn render(x: i32) -> bool {
    let s = "a";
    if x > 42 { return true; }
}
"#;
        let py = r#"# c
class Foo(Bar):
    def method(self, arg):
        pass
"#;
        // (label, table selector, lang, probe token)
        let probes: &[(&str, &str, &str, &str)] = &[
            ("comment", "comment", "rust", "c"),
            ("string", "string", "rust", "a"),
            ("keyword", "keyword", "rust", "if"),
            ("decl", "storage.type", "rust", "fn"),
            ("modifier", "storage.modifier", "rust", "pub"),
            ("function", "entity.name.function", "rust", "render"),
            ("type", "entity.name.class", "python", "Foo"),
            ("param", "variable.parameter", "python", "arg"),
            ("number", "constant.numeric", "rust", "42"),
            ("constant", "constant.language", "rust", "true"),
        ];
        // Redmean color distance (perceptual-ish, cheap): the same
        // metric the token palettes were authored with.
        fn dist(a: &str, b: &str) -> f64 {
            let c = |h: &str| {
                let h = h.trim_start_matches('#');
                (
                    u8::from_str_radix(&h[0..2], 16).unwrap() as f64,
                    u8::from_str_radix(&h[2..4], 16).unwrap() as f64,
                    u8::from_str_radix(&h[4..6], 16).unwrap() as f64,
                )
            };
            let (r1, g1, b1) = c(a);
            let (r2, g2, b2) = c(b);
            let (dr, dg, db) = (r1 - r2, g1 - g2, b1 - b2);
            let rm = (r1 + r2) / 2.0;
            ((2.0 + rm / 256.0) * dr * dr
                + 4.0 * dg * dg
                + (2.0 + (255.0 - rm) / 256.0) * db * db)
                .sqrt()
        }
        for def in KILIM_THEMES {
            for (name, table) in [
                (def.syntect_name, def.tokens),
                (def.neo_name, def.neo_tokens),
            ] {
                let expected = |selector: &str| {
                    table
                        .iter()
                        .find(|(s, _)| *s == selector)
                        .map(|(_, h)| *h)
                        .unwrap_or_else(|| panic!("{name}: no token entry for {selector}"))
                };
                let mut cols: Vec<(&str, String)> = Vec::new();
                for (label, selector, lang, tok) in probes {
                    let code = if *lang == "rust" { rust } else { py };
                    let got = ThemeRegistry::highlight(lang, code, name)
                        .into_iter()
                        .flatten()
                        .find(|s| s.text.trim() == *tok)
                        .unwrap_or_else(|| panic!("{name} never renders {tok}"))
                        .fg
                        .clone();
                    assert_eq!(got, expected(selector), "{name}: {label} token color");
                    cols.push((label, got));
                }
                // Every canonical element is visibly distinct: the
                // tables hold a >=60 design floor under this metric.
                for i in 0..cols.len() {
                    for j in (i + 1)..cols.len() {
                        let d = dist(&cols[i].1, &cols[j].1);
                        assert!(
                            d >= 55.0,
                            "{name}: {} {} and {} {} are too close (d={d:.0})",
                            cols[i].0,
                            cols[i].1,
                            cols[j].0,
                            cols[j].1
                        );
                    }
                }
            }
        }
    }
}
